### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by NJW007** [craymichael/CBP-16-Simulation#2]
First,thanks for your offer. When I run ./build.sh, a question appeared .Can you help me,thanks.

Step 8/13 : RUN scons $BUILD_TARGET -j `nproc`
 ---> Running in f9ef8f44bda0

scons: *** No SConstruct file found.
File "/usr/lib/python3/dist-packages/SCons/Script/Main.py", line 947, in _main
The command '/bin/sh -c scons $BUILD_TARGET -j `nproc`' returned a non-zero code: 2

**Comment by craymichael** [comment]
Hi - which file are you running? It has been some time since looking at this project, but I don't recall `build.sh` being a file included in this library. I am also not sure where `scons` comes into play. Is there more traceback?

**Comment by NJW007** [comment]
Thank you for your answer.I gave a wrong describe of this question. The question is when I run ./setup_cbp16.sh, a question accured. It seems that scons has a trouble.can you  help me?

Step 8/13 : RUN scons $BUILD_TARGET -j nproc
---> Running in f9ef8f44bda0

scons: *** No SConstruct file found.
File "/usr/lib/python3/dist-packages/SCons/Script/Main.py", line 947, in _main
The command '/bin/sh -c scons $BUILD_TARGET -j nproc' returned a non-zero code: 2

**Comment by NJW007** [comment]
Thank you. I have solved this question. When I run ./setup_cbp16.sh ,a question accured.
evaluationTraces.Final.tar: FAILED
trainingTraces.Final.tar: FAILED
md5sum: WARNING: 2 computed checksums did NOT match

**Comment by NJW007** [comment]
Thank  you for your answer. When I have successfully run ./setup_cbp16.sh,and then 
cd cbp16sim  
make
A question accured.
/usr/bin/ld: obj/simpython/simpython.o:simpython.cc:(.text.startup+0xfed): more undefined references to `_Py_Dealloc' follow
/usr/bin/ld: simpython.cc:(.text.startup+0x106f): undefined reference to `_Py_Dealloc'
/usr/bin/ld: simpython.cc:(.text.startup+0x1079): undefined reference to `PyErr_Print'
/usr/bin/ld: simpython.cc:(.text.startup+0x10aa): undefined reference to `_Py_Dealloc'

I  have installed python 2.7 and python 3.9. May be a mistake on C++ with Python, did you meet this when you run？

**Comment by craymichael** [comment]
You are missing the dev Python library files needed for compilation and linking here. If you are using Ubuntu, you can install the package libpython-dev I believe to fix the problem
