### ISSUE TITLE
Segmentation fault (core dumped) and new method not found

### ISSUE THREAD

**Issue by jeremiaaron** [craymichael/CBP-16-Simulation#4]
Hi! First of all, thank you for your code, it works fine for me with some adjustments needed.

However, when trying to implement a simple perceptron branch predictor (by Daniel Jimenez) in Python, I ran into segmentation fault when running the branch predictor.
```
Fatal Python error: Segmentation fault

Current thread 0x00007fe0df395740 (most recent call first):
<no Python frame>
Segmentation fault (core dumped)
```

After trying multiple things, I found that making a `def __init__(self):` method could be the culprit. My `__init__` method is as follows:
```
def __init__(self):
    self.perceptronSteps = 0
    self.ghr = bitarray('0' * HIST_LEN)
    self.perceptronTable = np.empty(shape=(TABLE_SIZE, HIST_LEN+1))
    self.perceptronTable.fill(0)
```

If I try to delete the `__init__` method, the segmentation fault does not appear anymore (well another error appears because I need the class variables initialized in the `__init__` method). How can I fix this error?

One more thing, when I tried to add a new method called `HashPC` to hash the PC with the global history register, the error
```
NameError: name 'HashPC' is not defined
```
appears. Is there another thing I should do to implement a new method in the PREDICTOR class? Thank you very much.

**Comment by jeremiaaron** [comment]
Wow, I just tried some things moments later after posting this issue and they worked.

I tried removing the `__slots__ = ()` line in the BASEPREDICTOR and PREDICTOR class, and the segmentation fault error disappeared.

Then, I found out that my HashPC method was missing the `self` argument and I did not call it using `self.`. So my working HashPC method now looks like this:
```
def HashPC(self, PC: UINT64) -> UINT64
```
and I call the method like this:
```
perceptronIndex = self.HashPC(PC)
```

I will mark this as closed, but I have a follow up question. What does the `__slots__ = ()`  line actually do? and do you have any idea why it might have caused segmentation fault? Thank you!

**Comment by craymichael** [comment]
Hi,

Glad you got it sorted! So, the `__slots__` attribute is a list of all attributes that the object has. Python will allocate memory only for these listed attributes. If this is unspecified (which is common in Python), then a dynamic size is used instead. The advantage of specifying it is that it reduces memory usage. The disadvantage is that it can cause errors like this and adds a little complexity to implementation. It is completely fine to remove it.
