### ISSUE TITLE
A question about CBP-4 files.

### ISSUE THREAD

**Issue by chnjstyj** [craymichael/CBP-16-Simulation#5]
Hi author. Your code works very well! But the trace of CBP-5 is huge spending much of time to training. Do you have copy of CBP-4 trace files? It is tiny more but I cannot download it in official website for the same reason of CBP-5 trace files. Thank you.

**Comment by craymichael** [comment]
Hi, glad to hear it! The data that I have can be downloaded [here](https://drive.google.com/drive/folders/1VAdmqdOEFLvnRKkQQidxvGJA_C6S2RWo). Unfortunately, I do not have CBP-4, only CBP-5.

**Comment by craymichael** [comment]
You may be able to reach out to the Program Chair about getting the data, if he still has it: https://moin.cc.gatech.edu/

**Comment by chnjstyj** [comment]
Thank you!
